site_name: Flight Prices ✈

nav:
  - Home: index.md
  - Installation: installation.md
  - Scripts: functions.md
  - About: about.md

plugins:
- mkdocstrings:
    default_handler: python

theme: readthedocs

repo_name: "gurezende/Flight_Prices"
repo_url: "https://github.com/gurezende/Flight_Prices"