[project]
name = "flightprices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "numpy>=2.1.3",
    "polars>=1.16.0",
    "pywhatkit>=5.4",
    "requests>=2.32.3",
    "selenium>=4.27.1",
    
]
